### ISSUE TITLE
[ENH]: Smaller image sizes

### ISSUE THREAD

**Issue by asreimer** [EarthCubeInGeo/resen-core#19]
As discussed in our meeting this week, we will work towards making a smaller resen-core image size by using system packages instead of conda.

We'll keep the helper scripts to be used to help others install packages on their own systems. Maybe we can create a different repository to host the helper scripts.

We also need to ensure that we keep the `start.sh` script (needed for https://github.com/EarthCubeInGeo/resen/issues/13) and any other scripts that we use are kept, which can be done by pulling them in from jupyter-stacks.

[An example Dockerfile that doesn't use Conda was prototyped by @pmreyes2 here.](https://github.com/pmreyes2/resen-core/blob/2c511f6554e266e63b2ce6f618dd45bfe6ccf504/resen-core/Dockerfile)

**Comment by ljlamarche** [comment]
This has been addressed by PR #32.  The image size without using conda is now 4.59GB.  Local testing has been successful, but the image still needs to be tested on the server.

**Comment by asreimer** [comment]
I think we can safely close this now since we have made a huge step forward and almost completely optimized the size of the image. It could probably be made a bit smaller yet, but we're essentially in the "chasing the 9s" phase of optimization.
