### ISSUE TITLE
moving fetching of data before updating locate database

### ISSUE THREAD

**Issue by pmreyes2** [EarthCubeInGeo/resen-core#20]
@asreimer We should probably move this:
https://github.com/EarthCubeInGeo/resen-core/blob/658a8e125f4dd676523867d2645c3b4e0a6df4e1/resen-core/Dockerfile#L130-L134
before the update of the `locate` database:
https://github.com/EarthCubeInGeo/resen-core/blob/658a8e125f4dd676523867d2645c3b4e0a6df4e1/resen-core/Dockerfile#L125-L128
what do you think?

**Comment by asreimer** [comment]
I think you were the one that changed the order here :)

In any case, https://github.com/EarthCubeInGeo/resen-core/commit/1015dc21a030e8b6e081e925dd26c911505ddab0 fixed that.
