### ISSUE TITLE
Adding pysat

### ISSUE THREAD

**Issue by ljlamarche** [EarthCubeInGeo/resen-core#27]
This is one of the recommendations from CEDAR (#26).  The [Python Satellite Data Analysis Toolkit (pysat)](https://pysat.readthedocs.io/en/latest/) provides a general framework for accessing satellite (and potentially other kinds) of data.  This lowers the barrier for entry for using different types of data, so it is well aligned with the InGeO goals.  Pysat 2.0 was recently released, so this is the version we should focus on including in resen-core.

**Comment by ljlamarche** [comment]
I believe @pmreyes2 has already made some progress on this, but I wanted to open an issue to keep track of where we are!

**Comment by ljlamarche** [comment]
Pysat can be successfully installed in both the py27 and py36 environments with:
```
LDFLAGS="-shared" pip install pysat
```
So far I've been able download cdf files and load them.  Everything seems to be working correctly, but I haven't tested all the features yet!

**Comment by asreimer** [comment]
I tested installing this in py36 and py27 as well without issue in the non-conda resen-core.

This biggest issue I have with installing pysat by default into resen-core is that it pulls in torch, which is 748.9MB! So installing in both environments increases the resen-core image size by ~25%.

Since we both didn't have any problems with installing pysat with pip and because it requires massive dependencies, I do not think we should add it. Users can install it trivially if they want it.

**Comment by valentic** [comment]
Weren't we thinking that pysat solves the problem of having a somewhat 
generic interface for downloading lots of different data types?  I  
agree that the size is too large. It seems like that package is 
following the typical course where these packages mushroom in size and 
start to try to do everything under the sun. It would seem that if pysat 
wants to do machine learning, then that should be a sub package instead 
of making everyone carry that baggage along.

**Comment by asreimer** [comment]
I completely agree. It pulls in a ton of dependencies to do a ton of things. It does provide a generic interface to many satellites for pulling and working with data. There's more work being done to add more instruments, such as AMISR, despite the project being called pysat :)

**Comment by asreimer** [comment]
Relevant: https://github.com/pytorch/pytorch/issues/17621 which explains why torch is so large. We don't really need this by default and haven't even gone down the road of exploring how to use GPUs to help with processing yet.

**Comment by astib** [comment]
It may be relevant to talk to pysat developers about this issue.

**Comment by asreimer** [comment]
With #74, this is done.
