### ISSUE TITLE
Add astropy

### ISSUE THREAD

**Issue by ljlamarche** [EarthCubeInGeo/resen-core#29]
[Astropy](https://www.astropy.org/) wasn't really developed for the CEDAR community, but I recently installed it in resen so I could look at FITS all-sky data (such as from Don Hampton's Poker Flats cameras).  It worked well for that purpose, so we might want to include it, although I think it can definitely wait until release 2.0.

The astropy documentation says it's included with anaconda, but I couldn't find it. Do we use miniconda in resen-core?  Regardless, I found it pretty straight forward to install.
```
conda install astropy
```
Running the astropy tests:
```
import astropy
astropy.test()
```
This reported some failures, but I could still use the package to do everything I wanted to do, so we would need to take a closer look at what exactly the issues were and if they were significant.

As a side note, what do we want the standard procedure to be for reporting packages to consider adding to resen-core?  I can just keep opening issues as I find things I needed to install manually unless someone has a better idea?

**Comment by pmreyes2** [comment]
[Astropy](https://www.astropy.org/)  would be a great addition. I use it for tracking the Cassiopeia A SNR with PFISR. You can also install [Astropy](https://www.astropy.org/)  with pip.

`pip install astropy`

And, to be able to run the test:

`pip install pytest-astropy`

The result of the test was the following:
```
import astropy
astropy.test()

```
```
...
==== 12124 passed, 351 skipped, 68 xfailed, 1926 warnings in 276.36 seconds ====
```
I am wondering if by installing with `conda` you also get the same number of passes/fails. I installed it in the virtual environment `py36`.

**Comment by ljlamarche** [comment]
I installed with conda and got a slightly different result from `astropy.test()`, but I really haven't looked into this enough to conclude the differences are due to the instillation.
```
==== 93 failed, 12034 passed, 350 skipped, 66 xfailed, 1928 warnings in 172.82 seconds ====
```

**Comment by pmreyes2** [comment]
The version of Astropy installed in `py36` using `pip` is `3.2.1`. `pytest` version is `4.3.1` I am wondering if that differs when installed with `conda`.

**Comment by asreimer** [comment]
Astropy added in https://github.com/EarthCubeInGeo/resen-core/pull/32

**Comment by ljlamarche** [comment]
Closing issue - #32 merged.
