### ISSUE TITLE
Add pymap3d

### ISSUE THREAD

**Issue by ljlamarche** [EarthCubeInGeo/resen-core#30]
[Pymap3d](https://github.com/scivision/pymap3d) is a coordinate conversion library.  It covers the kind of standard coordinate conversions (geodetic/ECEF/aer) that everyone has their own utilities for, but it's nice to just use them in a standard package.  I've installed and used pymap3d in both the py27 and py36 bucket environments without an issue.

**Comment by ljlamarche** [comment]
Minor point, but there are some functions that aren't vectorized in py27, but these kinds of quirks exist in a lot of code when you transition between python 2 and python 3.  I don't think it's anything to prevent us from adding it!

**Comment by asreimer** [comment]
I've added pymap3d in https://github.com/EarthCubeInGeo/resen-core/pull/32.

**Comment by ljlamarche** [comment]
Closing issue - #32 merged.
