### ISSUE TITLE
Add aacgmv2

### ISSUE THREAD

**Issue by ljlamarche** [EarthCubeInGeo/resen-core#33]
AACGM coordinates are a standard magnetic coordinate system that are used many places in the community.  This package is a wrapper around the [AACGM C library](http://superdarn.thayer.dartmouth.edu/aacgm.html), developed by Simon Shephard.

[aacgmv2 PyPI page](https://pypi.org/project/aacgmv2/)
[aacgmv2 git repository](https://github.com/aburrell/aacgmv2)
[aacgmv2 documentation](https://aacgmv2.readthedocs.io/en/stable/)

I have installed this using pip in the no-conda version of resen and used it without issue, but I haven't thoroughly tested it.

**Comment by asreimer** [comment]
I've added aacgmv2 in https://github.com/EarthCubeInGeo/resen-core/pull/32

**Comment by ljlamarche** [comment]
Closing issue - #32 merged.
